buildscript {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }

    dependencies {
        classpath 'com.palantir.jakartapackagealignment:jakarta-package-alignment:0.6.0'
        classpath 'com.palantir.gradle.jdks:gradle-jdks:0.74.0'
        classpath 'com.palantir.gradle.jdkslatest:gradle-jdks-latest:0.26.0'
        classpath 'com.diffplug.gradle:goomph:3.32.1'
        classpath 'com.palantir.gradle.externalpublish:gradle-external-publish-plugin:1.33.0'
        classpath 'com.palantir.gradle.failure-reports:gradle-failure-reports:1.18.0'
        classpath 'com.palantir.gradle.guide:gradle-guide:1.27.0'
        classpath 'com.palantir.gradle.idea-configuration:gradle-idea-configuration:0.8.0'
        classpath 'com.palantir.gradle.idea-language-injector:gradle-idea-language-injector:0.2.0'
        classpath 'com.palantir.gradle.consistentversions:gradle-consistent-versions:3.12.0'
        classpath 'com.palantir.gradle.plugintesting:gradle-plugin-testing:0.57.0'
        classpath 'com.gradle.publish:plugin-publish-plugin:2.0.0'
        classpath 'com.palantir.baseline-error-prone:gradle-baseline-error-prone:0.7.0'
        classpath 'com.palantir.baseline:gradle-baseline-java:7.2.0'
        classpath 'com.palantir.javaformat:gradle-palantir-java-format:2.88.0'
        classpath 'com.palantir.suppressible-error-prone:gradle-suppressible-error-prone:2.28.0'
    }
}

plugins {
id 'com.palantir.git-version' version '4.0.0'
}

apply plugin: 'com.palantir.external-publish'
apply plugin: 'com.palantir.failure-reports'
apply plugin: 'com.palantir.gradle-guide'
apply plugin: 'com.palantir.idea-language-injector'
apply plugin: 'com.palantir.jdks'
apply plugin: 'com.palantir.consistent-versions'
apply plugin: 'com.palantir.baseline'
apply plugin: 'com.palantir.baseline-error-prone-root'
apply plugin: 'com.palantir.baseline-java-versions'
apply plugin: 'com.palantir.jdks.latest'

allprojects {
    repositories {
        mavenCentral() { metadataSources { mavenPom(); ignoreGradleMetadataRedirection() } }
        gradlePluginPortal()
    }

    // Since we are using gradle-baseline in gradle-baseline we need to undo forces on project dependencies. Following
    // snippet forces the version to be the version originally resolved by gradle and not the force that nebula forced
    // it to.
    configurations.all { c ->
        c.resolutionStrategy { preferProjectModules() }
    }

    pluginManager.withPlugin('java') {
        tasks.withType(JavaCompile) {
            options.compilerArgs += ['-Werror']
            options.errorprone {
                // Temporarily disable some checks. Remove these line after upgrading Baseline.
                disable("DangerousIdentityKey")
                disable("ExecutorSubmitRunnableFutureIgnored")
                disable("IllegalSafeLoggingArgument")
                disable("ReadReturnValueIgnored")
                disable("UnsafeGaugeRegistration")
                disable("VarUsage")
                // End temporary disabled checks.

                disable("Slf4jLogsafeArgs")
                disable("PreferSafeLoggableExceptions")
                disable("PreferSafeLogger")
                disable("PreferSafeLoggingPreconditions")
                disable("PreconditionsConstantMessage")
            }
        }
    }

    apply plugin: 'com.palantir.java-format'
    apply plugin: 'com.palantir.jakarta-package-alignment'

    group = 'com.palantir.baseline'
    version System.env.CIRCLE_TAG ?: gitVersion()
    description = 'A Gradle plugin for applying Baseline-recommended build and IDE settings'
}

javaVersions {
    javaCompiler = 25
    libraryTarget = 17
}

jdks {
    daemonTarget = 21

    // Tests need these JDK versions installed
    jdkMajorVersionsToUse().addAll([11, 17, 21].collect { JavaLanguageVersion.of(it)})
}
