apply plugin: 'java-library'
apply plugin: 'com.palantir.external-publish-jar'

javaVersion {
    target = 17
    runtime = 21
}

dependencies {
    implementation 'com.google.code.findbugs:jsr305'
    implementation 'com.google.errorprone:error_prone_core'
    // Ensure a new enough version of dataflow-errorprone is available
    implementation 'io.github.eisop:dataflow-errorprone'

    testImplementation gradleApi()
    testImplementation 'com.palantir.tokens:auth-tokens'
    testImplementation 'com.fasterxml.jackson.core:jackson-annotations'
    testImplementation 'com.google.errorprone:error_prone_test_helpers'
    testImplementation 'com.palantir.safe-logging:preconditions'
    testImplementation 'com.palantir.safe-logging:preconditions-assertj'
    testImplementation 'com.palantir.safe-logging:safe-logging'
    testImplementation 'com.palantir.safe-logging:logger'
    testImplementation 'org.slf4j:slf4j-api'
    testImplementation 'org.apache.commons:commons-lang3'
    testImplementation 'commons-io:commons-io'
    testImplementation 'commons-lang:commons-lang'
    testImplementation 'org.assertj:assertj-core'
    testImplementation 'org.immutables:value::annotations'
    testImplementation 'org.jooq:jooq'
    testImplementation 'com.palantir.tritium:tritium-registry'
    testImplementation 'com.palantir.conjure.java:conjure-lib'
    testImplementation 'com.palantir.conjure.java.api:test-utils'
    testImplementation 'javax.ws.rs:javax.ws.rs-api'
    testCompileOnly 'org.immutables:value::annotations'
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-migrationsupport'
    testRuntimeOnly 'one.util:streamex'
    testRuntimeOnly 'com.fasterxml.jackson.module:jackson-module-afterburner'
    // for ForbidJavax
    testRuntimeOnly 'com.palantir.conjure.java.runtime:conjure-java-annotations'
    // for PreferCommonAnnotations
    testRuntimeOnly 'org.jetbrains:annotations'

    annotationProcessor 'com.google.auto.service:auto-service'
    compileOnly 'org.immutables:value::annotations'
    annotationProcessor 'org.immutables:value'
    testAnnotationProcessor 'org.immutables:value'
    compileOnly 'com.google.auto.service:auto-service'

    // This forces all errorprone configurations to use the same versions of dependencies used in the baseline-error-prone
    // repo at the time the baseline-error-prone was published (notably, the same version of error-prone itself). This
    // only works as GCV includes all the constraints from the `versions.props` in the `<dependencyManagement>` section
    // of the pom (like a bom would). We need this as when there are error-prone breaks, if the version of
    // error-prone is forced to be the same between the error-prone running this build and the error-prone being
    // used for compilation, we can't move past the breaks as our baseline-error-prones in this build are broken by
    // the new version of error-prone. So we force error-prone in this build back to the version that
    // baseline-error-prone expects while still using the new error-prone for compilation.
    // This trick could conceivable be used for suppressible-error-prone consumers in the gradle-suppressible-error-prone
    // plugin, but this would stop the version of error_prone_core etc lining up with error_prone_annotation(s) that
    // is being used by dependencies, which is less than ideal.
    errorprone enforcedPlatform('com.palantir.baseline:baseline-error-prone')
}


// Incorrectly identifies tests as junit4 usage
tasks.checkJUnitDependencies.enabled = false
tasks.withType(JavaCompile) {
    options.errorprone {
        disable('StrictUnusedVariable')
    }
}

// This is necessary to prevent the errorprone plugin from using this very project's output directory
// TODO(dsanduleac): this might not be necessary in gradle 6 anymore
def originalGroup = project.group
group = originalGroup + '-internal'
publishing.publications.maven {
    groupId = originalGroup
}

moduleJvmArgs {
    exports = [
        'jdk.compiler/com.sun.tools.javac.api',
        'jdk.compiler/com.sun.tools.javac.file',
        'jdk.compiler/com.sun.tools.javac.code',
        'jdk.compiler/com.sun.tools.javac.util',
        'jdk.compiler/com.sun.tools.javac.comp',
        'jdk.compiler/com.sun.tools.javac.main',
        'jdk.compiler/com.sun.tools.javac.model',
        'jdk.compiler/com.sun.tools.javac.parser',
        'jdk.compiler/com.sun.tools.javac.processing',
        'jdk.compiler/com.sun.tools.javac.tree',
        'jdk.compiler/com.sun.tools.javac.util'
    ]
    opens = ['jdk.compiler/com.sun.tools.javac.comp']
}
